import asyncio
from contextlib import suppress
from xoa_driver import (
    testers,
    modules,
    ports,
    enums,
    utils,
    exceptions
)
from xoa_driver.hlfuncs import (
    mgmt,
    cli
)

CHASSIS_IP = "10.20.1.166"
USERNAME = "xoa"
MODULE_IDX = 8
PORT_IDX = 0

async def my_awesome_func(stop_event: asyncio.Event):
    # create tester instance and establish connection
    async with testers.L23Tester(CHASSIS_IP, USERNAME) as tester:

        # access module 0 on the tester
        module = tester.modules.obtain(MODULE_IDX)
        if isinstance(module, modules.ModuleChimera):
            return None
        
        # access port 0 on the module as the TX port
        port = module.ports.obtain(PORT_IDX) #!Change to your port number!#

        await mgmt.reserve_port(port=port)

        # Configure port with .xpc file generated by ValkyrieManager
        await cli.port_config_from_file(port=port, path="port_config.xpc")

        # Configure port with CLI commands
        await cli.port_config_from_string(
            port=port,
            long_str="""
            P_RESET
            P_COMMENT \"This is a comment\"
            P_MACADDRESS  0xAAAAAABBBB99
            P_IPADDRESS  1.1.1.1 0.0.0.0 0.0.0.0 0.0.0.0
            """)
        
        # Release the port
        await mgmt.free_port(port)
        

async def main():
    stop_event = asyncio.Event()
    try:
        await my_awesome_func(stop_event)
    except KeyboardInterrupt:
        stop_event.set()


if __name__ == "__main__":
    asyncio.run(main())